server:
  port: 8081

spring:
  elrond:
    client:
      gateway: mainnet
      readTimeoutMillis: 5000
      writeTimeoutMillis: 5000
    api:
      url: mainnet
      readTimeoutMillis: 5000
      writeTimeoutMillis: 5000
